# Generated by Django 3.0.6 on 2020-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
    ]
