# Generated by Django 3.0.5 on 2020-07-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referrer',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
