# Generated by Django 3.0.5 on 2020-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referrer',
            field=models.CharField(default='None', max_length=15, null=True),
        ),
    ]
