# Generated by Django 3.0.6 on 2020-06-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_remove_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(default='Coming Soon', max_length=60),
        ),
    ]
