# Generated by Django 3.0.6 on 2020-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20200605_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_back',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_front',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
