# Generated by Django 3.0.5 on 2020-11-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20201102_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterField(
            model_name='identity',
            name='security_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
