# Generated by Django 3.0.6 on 2020-06-05 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_auto_20200605_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id_back',
            new_name='ID_Back',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id_front',
            new_name='ID_Front',
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in international format ie '+1234567890'.", regex='^\\+?1?\\d{9,15}')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
