# Generated by Django 3.0.5 on 2020-11-02 21:19

import broker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_auto_20201102_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to=broker.models.image_path),
        ),
        migrations.AlterField(
            model_name='identity',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to=broker.models.image_path),
        ),
    ]
