# Generated by Django 3.0.6 on 2020-06-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_auto_20200605_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='city',
        ),
    ]
