# Generated by Django 3.0.5 on 2021-01-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_auto_20201102_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
