# Generated by Django 3.0.6 on 2020-06-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_auto_20200605_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ID_Back',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ID_Front',
        ),
        migrations.AddField(
            model_name='customer',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
