# Generated by Django 3.0.6 on 2020-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_auto_20200605_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(error_messages={'invalid': 'erro here oo'}, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='back_id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='front_id'),
        ),
    ]
