# Generated by Django 3.0.6 on 2020-06-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_auto_20200605_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='increase',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
