# Generated by Django 3.0.6 on 2020-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_auto_20200606_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True),
        ),
    ]
