# Generated by Django 3.0.6 on 2020-06-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_trade_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='increase',
        ),
        migrations.AlterField(
            model_name='trade',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
