# Generated by Django 3.0.6 on 2020-06-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_auto_20200606_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='current',
        ),
        migrations.AddField(
            model_name='trade',
            name='increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
