# Generated by Django 3.0.6 on 2020-06-07 14:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0013_auto_20200606_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_back',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 450], upload_to='back_id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_front',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 450], upload_to='front_id'),
        ),
    ]
