# Generated by Django 3.0.6 on 2020-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0014_auto_20200607_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
