# Generated by Django 3.0.6 on 2020-06-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_trade_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
