# Generated by Django 3.0.6 on 2020-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0016_trade_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='current',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
