# Generated by Django 3.0.5 on 2020-06-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0017_trade_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='current',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='ratio',
        ),
    ]
