# Generated by Django 3.0.5 on 2020-06-07 21:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0018_auto_20200607_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='increase',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_back',
            field=django_resized.forms.ResizedImageField(crop=None, default='3d.png', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 450], upload_to='back_id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_front',
            field=django_resized.forms.ResizedImageField(crop=None, default='3d.png', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 450], upload_to='front_id'),
        ),
    ]
