# Generated by Django 3.0.5 on 2020-07-11 21:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0020_trade_increase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='note',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='increase',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='note',
        ),
        migrations.AddField(
            model_name='customer',
            name='referrer',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_back',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 450], upload_to='back_id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_front',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 450], upload_to='front_id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
