# Generated by Django 3.0.5 on 2020-07-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0021_auto_20200711_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
