# Generated by Django 3.0.5 on 2020-07-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0022_auto_20200712_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_front',
        ),
    ]
