# Generated by Django 3.0.5 on 2020-07-14 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0024_trade_withdrawal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='deposit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
