# Generated by Django 3.0.5 on 2020-07-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0026_auto_20200715_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
