# Generated by Django 3.0.5 on 2020-07-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0027_deposit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(default='primary', max_length=14),
        ),
    ]
