# Generated by Django 3.0.5 on 2020-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0028_auto_20200715_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hue',
            field=models.CharField(default='primary', max_length=14),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(default='Coming Soon', max_length=60),
        ),
    ]
